/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connect dbsetting;
    String driver, database, user, pass;
    Object tableTablean;

    public Login() {
        initComponents();

        dbsetting = new Connect();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        
        UIManager UI = new UIManager();
        UI.put("Panel.background", new ColorUIResource(40, 46, 57));
        UI.put("OptionPane.background", new ColorUIResource(40, 46, 57));
        UI.put("OptionPane.messageForeground", Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        Login = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        panelFormLogin = new PanelRound();
        labelLoginEmail = new javax.swing.JLabel();
        textLoginEmail = new TextFieldRound();
        labeLoginlPassword = new javax.swing.JLabel();
        textLoginPassword = new PasswordFieldRound();
        checkLoginShowPassword = new javax.swing.JCheckBox();
        buttonToRegister = new ButtonRound();
        buttonLogin = new ButtonRound();
        Register = new javax.swing.JPanel();
        labelRegister = new javax.swing.JLabel();
        panelFormRegister = new PanelRound();
        labelRegisterEmail = new javax.swing.JLabel();
        textRegisterEmail = new TextFieldRound();
        labelRegisterPassword = new javax.swing.JLabel();
        textRegisterPassword = new PasswordFieldRound();
        checkRegisterShowPassword = new javax.swing.JCheckBox();
        labelGender = new javax.swing.JLabel();
        radioGenderMale = new javax.swing.JRadioButton();
        radioGenderFemale = new javax.swing.JRadioButton();
        buttonToLogin = new ButtonRound();
        buttonRegister = new ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(22, 25, 32));
        Title.setPreferredSize(new java.awt.Dimension(640, 720));
        Title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("GAME STORE");
        labelTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        Title.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 330, 50));

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GAME STORE COVER.png"))); // NOI18N
        Title.add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 720));

        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Login.setBackground(new java.awt.Color(22, 25, 32));
        Login.setPreferredSize(new java.awt.Dimension(1280, 720));

        labelLogin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("LOGIN");

        labelLoginEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelLoginEmail.setForeground(new java.awt.Color(4, 175, 244));
        labelLoginEmail.setText("Email");

        labeLoginlPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labeLoginlPassword.setForeground(new java.awt.Color(4, 175, 244));
        labeLoginlPassword.setText("Password");

        checkLoginShowPassword.setBackground(new java.awt.Color(32, 49, 69));
        checkLoginShowPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkLoginShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        checkLoginShowPassword.setText("Show Password");
        checkLoginShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoginShowPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLoginLayout = new javax.swing.GroupLayout(panelFormLogin);
        panelFormLogin.setLayout(panelFormLoginLayout);
        panelFormLoginLayout.setHorizontalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkLoginShowPassword)
                    .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                        .addComponent(textLoginEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLoginEmail)
                        .addComponent(labeLoginlPassword)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelFormLoginLayout.setVerticalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelLoginEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labeLoginlPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkLoginShowPassword)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        buttonToRegister.setBackground(new java.awt.Color(22, 25, 32));
        buttonToRegister.setForeground(new java.awt.Color(103, 193, 245));
        buttonToRegister.setText("Don't have an account?");
        buttonToRegister.setBorderColor(new java.awt.Color(22, 25, 32));
        buttonToRegister.setColor(new java.awt.Color(22, 25, 32));
        buttonToRegister.setColorClick(new java.awt.Color(22, 12, 18));
        buttonToRegister.setColorOver(new java.awt.Color(22, 52, 84));
        buttonToRegister.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buttonToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToRegisterActionPerformed(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(0, 96, 213));
        buttonLogin.setText("LOGIN");
        buttonLogin.setBorderColor(new java.awt.Color(0, 96, 213));
        buttonLogin.setColor(new java.awt.Color(0, 96, 213));
        buttonLogin.setColorClick(new java.awt.Color(0, 45, 210));
        buttonLogin.setColorOver(new java.awt.Color(0, 148, 206));
        buttonLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(labelLogin))
                    .addComponent(panelFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(buttonToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(labelLogin)
                .addGap(50, 50, 50)
                .addComponent(panelFormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        tabbedPane.addTab("tab1", Login);

        Register.setBackground(new java.awt.Color(22, 25, 32));
        Register.setPreferredSize(new java.awt.Dimension(1280, 720));

        labelRegister.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelRegister.setForeground(new java.awt.Color(255, 255, 255));
        labelRegister.setText("REGISTER");

        labelRegisterEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelRegisterEmail.setForeground(new java.awt.Color(4, 175, 244));
        labelRegisterEmail.setText("Email");

        labelRegisterPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelRegisterPassword.setForeground(new java.awt.Color(4, 175, 244));
        labelRegisterPassword.setText("Password");

        checkRegisterShowPassword.setBackground(new java.awt.Color(32, 49, 69));
        checkRegisterShowPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkRegisterShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        checkRegisterShowPassword.setText("Show Password");
        checkRegisterShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRegisterShowPasswordActionPerformed(evt);
            }
        });

        labelGender.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelGender.setForeground(new java.awt.Color(4, 175, 244));
        labelGender.setText("Gender");

        radioGenderMale.setBackground(new java.awt.Color(32, 49, 69));
        radioGenderMale.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioGenderMale.setForeground(new java.awt.Color(255, 255, 255));
        radioGenderMale.setText("Male");

        radioGenderFemale.setBackground(new java.awt.Color(32, 49, 69));
        radioGenderFemale.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioGenderFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioGenderFemale.setText("Female");

        javax.swing.GroupLayout panelFormRegisterLayout = new javax.swing.GroupLayout(panelFormRegister);
        panelFormRegister.setLayout(panelFormRegisterLayout);
        panelFormRegisterLayout.setHorizontalGroup(
            panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormRegisterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelFormRegisterLayout.createSequentialGroup()
                            .addComponent(labelGender)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                            .addComponent(checkRegisterShowPassword))
                        .addComponent(textRegisterPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textRegisterEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRegisterEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelRegisterPassword, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panelFormRegisterLayout.createSequentialGroup()
                        .addComponent(radioGenderMale)
                        .addGap(99, 99, 99)
                        .addComponent(radioGenderFemale)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelFormRegisterLayout.setVerticalGroup(
            panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormRegisterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelRegisterEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelRegisterPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormRegisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkRegisterShowPassword))
                    .addGroup(panelFormRegisterLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelGender)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGenderMale)
                    .addComponent(radioGenderFemale))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        buttonToLogin.setBackground(new java.awt.Color(22, 25, 32));
        buttonToLogin.setForeground(new java.awt.Color(103, 193, 245));
        buttonToLogin.setText("Already have an account?");
        buttonToLogin.setBorderColor(new java.awt.Color(22, 25, 32));
        buttonToLogin.setColor(new java.awt.Color(22, 25, 32));
        buttonToLogin.setColorClick(new java.awt.Color(22, 12, 18));
        buttonToLogin.setColorOver(new java.awt.Color(22, 52, 84));
        buttonToLogin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buttonToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToLoginActionPerformed(evt);
            }
        });

        buttonRegister.setText("REGISTER");
        buttonRegister.setBorderColor(new java.awt.Color(111, 166, 32));
        buttonRegister.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(labelRegister))
                    .addComponent(panelFormRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(buttonToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(labelRegister)
                .addGap(50, 50, 50)
                .addComponent(panelFormRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        tabbedPane.addTab("tab2", Register);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -30, 660, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkLoginShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoginShowPasswordActionPerformed
        if (checkLoginShowPassword.isSelected()) {
            textLoginPassword.setEchoChar((char) 0);
        } else {
            textLoginPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkLoginShowPasswordActionPerformed

    private void buttonToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToRegisterActionPerformed
        tabbedPane.setSelectedComponent(Register);
    }//GEN-LAST:event_buttonToRegisterActionPerformed

    private void checkRegisterShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRegisterShowPasswordActionPerformed
        if (checkRegisterShowPassword.isSelected()) {
            textRegisterPassword.setEchoChar((char) 0);
        } else {
            textRegisterPassword.setEchoChar('*');
        }

    }//GEN-LAST:event_checkRegisterShowPasswordActionPerformed

    private void buttonToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToLoginActionPerformed
        tabbedPane.setSelectedComponent(Login);
    }//GEN-LAST:event_buttonToLoginActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        String data[] = new String[3];
        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            Statement stt = conn.createStatement();

            String gender = "";
            if (radioGenderMale.isSelected()) {
                gender = "male";
            } else if (radioGenderFemale.isSelected()) {
                gender = "female";
            } else {
                JOptionPane.showMessageDialog(null, "Please select your gender");
            }
            String SQL = "INSERT INTO users (name, email, gender) VALUES "
                    + "("
                    + "'" + textRegisterPassword.getText() + "', "
                    + "'" + textRegisterEmail.getText() + "', "
                    + "'" + gender + "'"
                    + ")";
            stt.executeUpdate(SQL);

            String SQL2 = "SELECT * FROM users WHERE userID=(SELECT max(userID) FROM users)";
            ResultSet res = stt.executeQuery(SQL2);
            if (res.next()) {
                System.out.println(res.getString(1));
                JOptionPane.showMessageDialog(null, "Data has been saved", "Saved", JOptionPane.INFORMATION_MESSAGE);
            } else if (textRegisterEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out username");
            } else if (textRegisterPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out password");
            }
            stt.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);

            Statement stt = conn.createStatement();
            String SQL = "SELECT * FROM users WHERE email='" + textLoginEmail.getText() + "' AND name='" + textLoginPassword.getText() + "'";
            ResultSet res = stt.executeQuery(SQL);
            if (res.next()) {
                UserFrame userframe = new UserFrame(Integer.parseInt(res.getString(1)));
                userframe.setVisible(true);
                this.setVisible(false);
            } else if (textLoginEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out username");
            } else if (textLoginPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill out password");
            } else if (textLoginEmail.getText().contains("admin@gmail.com") && textLoginPassword.getText().contains("Admin")) {
                AdminFrame adminframe = new AdminFrame();
                adminframe.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong username or password!", "Message", JOptionPane.ERROR_MESSAGE);
            }
            stt.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel Title;
    private ButtonRound buttonLogin;
    private ButtonRound buttonRegister;
    private ButtonRound buttonToLogin;
    private ButtonRound buttonToRegister;
    private javax.swing.JCheckBox checkLoginShowPassword;
    private javax.swing.JCheckBox checkRegisterShowPassword;
    private javax.swing.JLabel labeLoginlPassword;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLoginEmail;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelRegisterEmail;
    private javax.swing.JLabel labelRegisterPassword;
    private javax.swing.JLabel labelTitle;
    private PanelRound panelFormLogin;
    private PanelRound panelFormRegister;
    private javax.swing.JRadioButton radioGenderFemale;
    private javax.swing.JRadioButton radioGenderMale;
    private javax.swing.JTabbedPane tabbedPane;
    private TextFieldRound textLoginEmail;
    private PasswordFieldRound textLoginPassword;
    private TextFieldRound textRegisterEmail;
    private PasswordFieldRound textRegisterPassword;
    // End of variables declaration//GEN-END:variables
}
