
import java.awt.Dimension;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
        JButton btn = new JButton("Aku");
        btn.setPreferredSize(new Dimension(100, 50));
        JButton btn1 = new JButton("Kamu");
        btn.setPreferredSize(new Dimension(100, 50));
        JButton btn2 = new JButton("Kalian");
        btn.setPreferredSize(new Dimension(100, 50));
        JButton btn3 = new JButton("Kita");
        btn.setPreferredSize(new Dimension(100, 50));
        JButton btn4 = new JButton("SEMUA");
        btn.setPreferredSize(new Dimension(100, 50));
        panel.add(btn);
        panel.add(btn1);
        panel.add(btn2);
        panel.add(btn3);
        panel.add(btn4);
        panel.revalidate();
        panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonMyGames = new ButtonRound();
        buttonStore = new ButtonRound();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCoba = new javax.swing.JPanel();
        labelMyGames1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new PanelRound();
        jPanel2 = new javax.swing.JPanel();
        labelMyGames = new javax.swing.JLabel();
        panelRound1 = new PanelRound();
        buttonReset = new ButtonRound();
        buttonReset1 = new ButtonRound();
        buttonReset2 = new ButtonRound();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        buttonMyGames.setBackground(new java.awt.Color(0, 0, 0));
        buttonMyGames.setForeground(new java.awt.Color(158, 158, 158));
        buttonMyGames.setText("MY GAMES");
        buttonMyGames.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonMyGames.setColor(new java.awt.Color(0, 0, 0));
        buttonMyGames.setColorClick(new java.awt.Color(0, 0, 0));
        buttonMyGames.setColorOver(new java.awt.Color(30, 30, 30));
        buttonMyGames.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonMyGames.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonMyGames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMyGamesMouseClicked(evt);
            }
        });

        buttonStore.setBackground(new java.awt.Color(0, 0, 0));
        buttonStore.setForeground(new java.awt.Color(158, 158, 158));
        buttonStore.setText("STORE");
        buttonStore.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonStore.setColor(new java.awt.Color(0, 0, 0));
        buttonStore.setColorClick(new java.awt.Color(0, 0, 0));
        buttonStore.setColorOver(new java.awt.Color(30, 30, 30));
        buttonStore.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonStore.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStoreMouseClicked(evt);
            }
        });
        buttonStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buttonMyGames, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStore, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMyGames, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStore, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        panelCoba.setBackground(new java.awt.Color(22, 25, 32));

        labelMyGames1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelMyGames1.setForeground(new java.awt.Color(255, 255, 255));
        labelMyGames1.setText("UWOGH");

        jScrollPane1.setOpaque(false);

        panel.setPreferredSize(new java.awt.Dimension(1080, 150));
        panel.setLayout(new java.awt.GridLayout(2, 3, 10, 10));
        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout panelCobaLayout = new javax.swing.GroupLayout(panelCoba);
        panelCoba.setLayout(panelCobaLayout);
        panelCobaLayout.setHorizontalGroup(
            panelCobaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCobaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelCobaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMyGames1))
                .addContainerGap())
        );
        panelCobaLayout.setVerticalGroup(
            panelCobaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCobaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelMyGames1)
                .addGap(119, 119, 119)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panelCoba);

        jPanel2.setBackground(new java.awt.Color(22, 25, 32));

        labelMyGames.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelMyGames.setForeground(new java.awt.Color(255, 255, 255));
        labelMyGames.setText("MY GAMES");

        buttonReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonReset.setForeground(new java.awt.Color(103, 193, 245));
        buttonReset.setBorderColor(new java.awt.Color(39, 59, 75));
        buttonReset.setColor(new java.awt.Color(39, 59, 75));
        buttonReset.setColorClick(new java.awt.Color(19, 39, 55));
        buttonReset.setColorOver(new java.awt.Color(79, 99, 115));
        buttonReset.setPreferredSize(new java.awt.Dimension(330, 150));
        buttonReset.setRadius(0);

        buttonReset1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonReset1.setForeground(new java.awt.Color(103, 193, 245));
        buttonReset1.setBorderColor(new java.awt.Color(39, 59, 75));
        buttonReset1.setColor(new java.awt.Color(39, 59, 75));
        buttonReset1.setColorClick(new java.awt.Color(19, 39, 55));
        buttonReset1.setColorOver(new java.awt.Color(79, 99, 115));
        buttonReset1.setPreferredSize(new java.awt.Dimension(330, 150));
        buttonReset1.setRadius(0);

        buttonReset2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonReset2.setForeground(new java.awt.Color(103, 193, 245));
        buttonReset2.setBorderColor(new java.awt.Color(39, 59, 75));
        buttonReset2.setColor(new java.awt.Color(39, 59, 75));
        buttonReset2.setColorClick(new java.awt.Color(19, 39, 55));
        buttonReset2.setColorOver(new java.awt.Color(79, 99, 115));
        buttonReset2.setPreferredSize(new java.awt.Dimension(330, 150));
        buttonReset2.setRadius(0);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonReset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonReset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonReset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMyGames)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelMyGames)
                .addGap(98, 98, 98)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(22, 25, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(22, 25, 32));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 1280, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMyGamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMyGamesMouseClicked

    }//GEN-LAST:event_buttonMyGamesMouseClicked

    private void buttonStoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStoreMouseClicked

    private void buttonStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonRound buttonMyGames;
    private ButtonRound buttonReset;
    private ButtonRound buttonReset1;
    private ButtonRound buttonReset2;
    private ButtonRound buttonStore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelMyGames;
    private javax.swing.JLabel labelMyGames1;
    private PanelRound panel;
    private javax.swing.JPanel panelCoba;
    private PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
